# Generated by Django 3.1.7 on 2021-02-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipBluda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Bluda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cena', models.FloatField(default=0, verbose_name='Цена')),
                ('gramovka', models.FloatField(default=0, verbose_name='Граммовка')),
                ('prevyu', models.ImageField(upload_to='', verbose_name='Превью')),
                ('tip_bluda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.tipbluda', verbose_name='Тип блюда')),
            ],
        ),
    ]
