# Generated by Django 3.1.7 on 2021-02-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='bluda',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='tipbluda',
            options={'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюда'},
        ),
        migrations.CreateModel(
            name='IngridientiVBlude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bludo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.bluda', verbose_name='Блюда')),
                ('ingridient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.ingridienti', verbose_name='Ингридиенты')),
            ],
            options={
                'verbose_name': 'Ингридиент в блюде',
                'verbose_name_plural': 'Ингридиенты в блюде',
            },
        ),
    ]
