# Generated by Django 3.1.7 on 2021-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0002_auto_20210226_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridientivblude',
            name='gramovka',
            field=models.FloatField(default=0, verbose_name='Граммовка'),
            preserve_default=False,
        ),
    ]
