# Generated by Django 3.1.7 on 2021-02-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0003_ingridientivblude_gramovka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akzia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposob_otdachi', models.IntegerField(choices=[('Самовывоз', 1), ('Доставка курьером', 2), ('На месте', 3)], verbose_name='Способ отдачи')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('data_i_vremia_zakaza', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('stolik', models.IntegerField(blank=True, null=True, verbose_name='Номер столика')),
                ('akzia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.akzia', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
