# Generated by Django 3.1.7 on 2021-02-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0004_akzia_zakaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('cena', models.FloatField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тары',
            },
        ),
        migrations.CreateModel(
            name='DetaliZakaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost_na_moment_realizazii', models.FloatField(blank=True, null=True, verbose_name='Цена на момент реализации')),
                ('bludo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.bluda', verbose_name='Блюдо')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udachi.zakaz', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
        migrations.AddField(
            model_name='bluda',
            name='tara_po_umolchaniu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.tara', verbose_name='Тара по умолчанию'),
        ),
    ]
