# Generated by Django 3.1.7 on 2021-03-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udachi', '0005_auto_20210226_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bronirovanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vremia', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tелефон')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('status_bronirovania', models.BooleanField(default=False, verbose_name='Бронь  подтверждена')),
                ('predoplata', models.BooleanField(default=False, verbose_name='Предоплата')),
                ('stolik', models.IntegerField(blank=True, null=True, verbose_name='Номер столика')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='IngridientiNaSklade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField(default=0, verbose_name='Кол-во')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udachi.ingridienti', verbose_name='Ингридиент')),
            ],
            options={
                'verbose_name': 'Ингридиент на складе',
                'verbose_name_plural': 'Ингридиенты на складе',
            },
        ),
        migrations.CreateModel(
            name='IstoriaizmeneniaNaSkladax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_operazii', models.IntegerField(choices=[(1, 'Поступление'), (2, 'Спиисание'), (3, 'Реализация'), (4, 'Перемещение')], default=1, verbose_name='Тип операции')),
                ('data_i_vremia', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('kolvo', models.FloatField(default=0, verbose_name='Кол-во')),
                ('cena_na_moment_zakupki', models.FloatField(blank=True, null=True, verbose_name='Цена на момент закупки')),
                ('ingridient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.ingridienti', verbose_name='Ингридиент')),
                ('ispolnitel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'История измененения на складе',
                'verbose_name_plural': 'Истории измененения на складе',
            },
        ),
        migrations.CreateModel(
            name='Postavshiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=255, verbose_name='Наименование')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tелефон')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Sotrudnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tелефон')),
                ('data_rozdenia', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.RemoveField(
            model_name='bluda',
            name='tara_po_umolchaniu',
        ),
        migrations.DeleteModel(
            name='Tara',
        ),
        migrations.AddField(
            model_name='istoriaizmenenianaskladax',
            name='sklad_kuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sklad_kuda_istoria', to='udachi.sklad', verbose_name='Склад куда'),
        ),
        migrations.AddField(
            model_name='istoriaizmenenianaskladax',
            name='sklad_otkuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sklad_otkuda_istoria', to='udachi.sklad', verbose_name='Склад откуда'),
        ),
        migrations.AddField(
            model_name='ingridientinasklade',
            name='sklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udachi.sklad', verbose_name='Склад'),
        ),
    ]
