# Generated by Django 3.1.7 on 2021-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0006_auto_20210312_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='zakaz_proveden',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заказ проведен'),
        ),
    ]
