# Generated by Django 3.1.7 on 2021-03-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0007_zakaz_zakaz_proveden'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluda',
            name='kolvo_dobavlenia_v_korzinu',
            field=models.IntegerField(default=0, verbose_name='Кол-во раз добавили в корзину'),
        ),
        migrations.AddField(
            model_name='bluda',
            name='ne_pokazivat',
            field=models.BooleanField(default=False, verbose_name='Не показывать блюдо'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='sposob_otdachi',
            field=models.IntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка курьером'), (3, 'На месте')], verbose_name='Способ отдачи'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
