# Generated by Django 3.1.7 on 2021-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0008_auto_20210313_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otzivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_otziva', models.DateTimeField(auto_created=True, verbose_name='Дата')),
                ('avtor', models.CharField(max_length=255, verbose_name='Автор')),
                ('otziv', models.TextField(verbose_name='Отзыв')),
                ('telephone_avtora', models.CharField(max_length=255, verbose_name='Автор')),
                ('prosli_moderaziu', models.BooleanField(default=False, verbose_name='Модерацию прошли')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
