# Generated by Django 3.1.7 on 2021-04-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akzia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Otzivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=255, verbose_name='Автор')),
                ('otziv', models.TextField(verbose_name='Отзыв')),
                ('telephone_avtora', models.CharField(max_length=255, verbose_name='Телефон автора')),
                ('data_otziva', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('prosli_moderaziu', models.BooleanField(default=False, verbose_name='Модерацию прошли')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='TipTovara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип Товарв',
                'verbose_name_plural': 'Типы товара',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('data_i_vremia_zakaza', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('status_zakaza', models.IntegerField(choices=[(1, 'Оплачено'), (2, 'В пути'), (3, 'Выдано')], verbose_name='Статус заказа')),
                ('akzia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lapa.akzia', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cena', models.FloatField(default=0, verbose_name='Цена')),
                ('prevyu', models.ImageField(upload_to='', verbose_name='Превью')),
                ('kolvo_dobavlenia_v_korzinu', models.IntegerField(default=0, verbose_name='Кол-во раз добавили в корзину')),
                ('tip_tovara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lapa.tiptovara', verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Sotrudnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tелефон')),
                ('data_rozdenia', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='DetaliZakaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost_na_moment_realizazii', models.FloatField(blank=True, null=True, verbose_name='Цена на момент реализации')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lapa.tovar', verbose_name='Товар')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapa.zakaz', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
    ]
